### ISSUE TITLE
Add UI feature that links to wildfire maps

### ISSUE THREAD

**Issue by timhitchins** [timhitchins/rose-city-resource#20]
The UI needs to be update to include an interactive feature that links to the outside wildfire map.  I am not the sure of the best way to do this-- whether a button or some other feature best solves it.  Would love feedback.  

Thoughts to consider:
- this will link to an outside resource
- we want to avoid cluttering the UI / need to consider #19 
- what did I miss?

cc @isthewhiz @wrunion

**Comment by wrunion** [comment]
I know we talked this through but here's the summary for the GitHub record: we decided to nix this feature, since it would require us to change too much of the UI for something temporary. 

We also didn't like the idea of linking to an external site, and building a separate route/redirect page was unnecessarily cumbersome.

Unless there's anything else to address, I think it's safe to close this issue!
